#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    Sdotool
#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.


_bin="$(
  dirname \
    "$(command \
        -v \
        "env")")"
_lib="$(
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" \
  2>"/dev/null" || \
  source \
    "${_crash_bash}"

# shellcheck disable=SC2034
_global_variables() {
  target_command=""
  target_keys=()
  target_value=""
  event_device=""
  print_keyevents=""
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    "key2keyevent" \
    "android-input-utils"
  _check_cmd \
    "su" \
    "sudo"
}

_key_send() {
  local \
    _keys=() \
    _key \
    _keyevent \
    _cmd=()
  _keys+=(
    "$@"
  )
  for _key in "${_keys[@]}"; do
    _msg=(
      "Sending key '${_key}'"
    )
    _msg_info \
      "${_msg[*]}"
    _keyevent="$(
      _keyevent_get \
        "${_key}")"
    if [[ "${_keyevent}" == "" ]]; then
      _keyevent="$(
        key2keyevent \
          "${_key}")"
      if [[ "${_keyevent}" == "" ]]; then
        _msg=(
          "Key '${_key}' not recorded."
        )
        _msg_error \
          "${_msg[*]}" \
          1
      fi
      _msg=(
        "Sending ${_key} -> ${_keyevent}."
      )
      _msg_info \
        "${_msg[*]}"
    else
      _msg=(
        "Sending ${_key} -> ${_keyevent}."
      )
      _msg_info \
        "${_msg[*]}"
    fi
    _cmd=(
      input
        keyevent
        "${_keyevent}"
      )
    sudo \
      "${_cmd[@]}"
  done
  true
}

_keyaction_send() {
  local \
    _event_device="${1}" \
    _action="${2}" \
    _keys=() \
    _key \
    _null_args=() \
    _action_args=() \
    _sendevent_args=() \
    _cmd=()
  _sendevent_args+=(
    "${_event_device}"
  )
  _null_args+=(
    "${_sendevent_args[@]}"
    0 0 0
  )
  shift \
    2
  _keys+=(
    "$@"
  )
  if [[ "${_action}" == "down" ]]; then
    _action_modifier=1
  elif [[ "${_action}" == "up" ]]; then
    _action_modifier=0
  fi
  for _key in "${_keys[@]}"; do
    _action_event=(
      1 "${_key}" "${_action_modifier}"
    )
    _action_args=(
      "${_sendevent_args[@]}"
      "${_action_event[@]}"
    )
    _msg=(
      "Running 'sendevent'"
      "with arguments '${_action_args[*]}'."
    )
    _cmd=(
      sendevent \
        "${action_args[@]}"
      "&&"
      sendevent \
        "${_sendevent_args[@]}"
        "${_null_event[@]}"
    )
    su \
      -c \
        "${_cmd[*]}"
  done
}

_keyevents_get() {
  local \
    _key2keyevent_opts=()
  if [[ "${quiet}" == "n" ]]; then
    _key2keyevent_opts+=(
      -v
    )
  fi
  _key2keyevent_opts+=(
    -P
  )
  key2keyevent \
    "${_key2keyevent_opts[@]}"
}

_sdotool() {
  local \
    _command="${1}" \
    _print_keyevents="${2}" \
    _event_device="${3}" \
    _keys=() \
    _args=() \
    _cmd \
    _msg=()
  shift \
    3
  _keys+=(
    "$@"
  )
  if [[ "${_print_keyevents}" == "y" ]]; then
    _keyevents_get
  fi
  if [[ "${_command}" == "key" ]]; then
    _cmd="key_send"
    _args+=(
      "${_keys[@]}"
    )
  elif [[ "${_command}" == "keydown" ]]; then
    _cmd="keyaction_send"
    _args+=(
      "${_event_device}"
      "down"
      "${_keys[@]}"
    )
  elif [[ "${_command}" == "keyup" ]]; then
    _cmd="keyaction_send"
    _args+=(
      "${_event_device}"
      "up"
      "${_keys[@]}"
    )
  else
    _msg=(
      "Unknown command '${_command}'."
    )
    _msg_info \
      "${_msg[*]}"
  fi
  "_${_cmd}" \
    "${_args[@]}"
}

_set_overrides() {
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  _set_override \
    "print" \
    "keyevents" \
    "n"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _exit_code="${1}" \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

command-line Surfaceflinger automation tool

usage:
  ${app_name}
    [options]
    <command>
    (<argument>)

  commands:
     key                  Send key event corresponding to symbol
                          <symbol>
     keydown              Send input event corresponding to pressing
                          key symbol <symbol> and keeping it pressed.
     keyup                Send input event corresponding to releasing
                          key symbol <symbol>.

  options:

     -a                   Prints a list of all the possible
                          symbols which can be sent.
                          Default: ${print_keyevents}

     -e <event-device>    Path of the event device to target for
                          the 'keydown' and 'keyup' commands.
                          By defaults it targets 'event0' because
                          it usually is the keyboard, but you
                          may want to check with 'getevent'.
                          Default: ${event_device}

     -h                   This message.
     -c                   Enable color output
     -v                   Enable verbose output

ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${_exit_code}"
}

_display_flags() {
  local \
    _flags=(
      "${1}"
    ) \
    _flag
  for _flag \
    in "${_flags[@]}"; do
  _msg_info \
    "                             ${_flag}"
  done
}

# Shows configuration options.
_show_config() {
  local \
    _get_date
  TZ=UTC \
    printf \
      -v _get_date \
      '%(%FT%R%z)T' \
      "${SOURCE_DATE_EPOCH}"
  _msg_info "${app_name} configuration"
  _msg_info "           Operation date:   ${_get_date}"
  _msg_info "           Target command:   ${target_command}"
  _msg_info "          Print keyevents:   ${print_keyevents}"
  _msg_info "             Event device:   ${event_device}"
  _msg_info "              Target keys:   ${target_keys[*]}"
}

_globals
_global_variables
_requirements
_config_user_init \
  "${app_name}"
# shellcheck disable=SC2034
while \
  getopts \
    'ae:cvh?' \
    arg; do
  case \
    "${arg}" in
    a)
      override_print_keyevents="y" ;;
    e)
      override_event_device="${OPTARG}" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg=(
        "Invalid argument '${arg}'."
      )
      _msg_error \
        "${_msg[*]}" \
        0
      _usage \
        1 ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( $# < 1 )); then
  _msg=(
    "No command given."
  )
  _msg_error \
    "${_msg[*]}" \
    0
  _set_overrides
  _usage \
    1
fi
target_command="${1}"
shift \
  1
if (( 0 < $# )); then
  target_keys+=(
    "$@"
  )
else
  _msg=(
    "No arguments given."
  )
  _msg_error \
    "${_msg[*]}" \
    0
  _set_overrides
  _usage \
    1
fi
_set_overrides
_show_config
app_opts=(
  "${target_command}"
  "${print_keyevents}"
  "${event_device}"
  "${target_keys[@]}"
)
_sdotool \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
